name: Build Release Artifacts

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install -y -qq libmbedtls-dev
      - run: source tools/ci.sh && build_release_amalgamation
      - run: gh release upload ${{ github.ref_name }} build/open62541.{c,h}
        env:
          GH_TOKEN: ${{ github.token }}
